# Generated by Django 2.2 on 2020-02-26 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'In active'), ('1', 'Active')], default=0, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'In active'), ('1', 'Active')], default=0, max_length=200)),
                ('courses', models.ManyToManyField(to='api.Course')),
            ],
            options={
                'verbose_name_plural': 'lecturers',
                'db_table': 'lecturers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('regno', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'In active'), ('1', 'Active')], default=0, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
            options={
                'verbose_name_plural': 'students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentLogBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateField()),
                ('worked_on', models.CharField(max_length=500, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'Not Approved'), ('1', 'Approved')], default=0, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name_plural': 'student_logbook_items',
                'db_table': 'student_logbook_items',
            },
        ),
        migrations.CreateModel(
            name='StudentLogBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'Not Approved'), ('1', 'Approved')], default=0, max_length=200)),
                ('logbook_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StudentLogBookItem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name_plural': 'student_logbooks',
                'db_table': 'student_logbooks',
            },
        ),
        migrations.CreateModel(
            name='LecturerStudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'In active'), ('1', 'Active')], default=0, max_length=200)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lecturer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name_plural': 'lecturer_student_assignments',
                'db_table': 'lecturer_student_assignments',
            },
        ),
    ]
