# Generated by Django 2.2 on 2020-02-26 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
