# Generated by Django 2.2 on 2020-08-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogbookitem',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentlogbookitem',
            name='logbook',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.StudentLogBook'),
        ),
    ]
