# Generated by Django 2.2 on 2020-02-26 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200226_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
