# Generated by Django 2.2 on 2020-08-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200816_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogbook',
            name='label',
            field=models.CharField(default='Default Logbook', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentlogbookitem',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
