# Generated by Django 2.2 on 2020-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200820_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[(0, 'In active'), (1, 'Active')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='lecturerstudentassignment',
            name='status',
            field=models.CharField(choices=[(0, 'In active'), (1, 'Active')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentlogbook',
            name='status',
            field=models.CharField(choices=[(0, 'Not Approved'), (1, 'Approved')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentlogbookitem',
            name='status',
            field=models.CharField(choices=[(0, 'Not Approved'), (1, 'Approved')], default=0, max_length=200),
        ),
    ]
