# Generated by Django 2.2 on 2020-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200226_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogbook',
            name='logbook_item',
        ),
        migrations.AddField(
            model_name='studentlogbook',
            name='logbook_item',
            field=models.ManyToManyField(to='api.StudentLogBookItem'),
        ),
    ]
