# Generated by Django 2.2 on 2020-02-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200226_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlogbook',
            old_name='logbook_item',
            new_name='logbook_items',
        ),
    ]
