# Generated by Django 2.2 on 2020-10-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200823_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerstudentassignment',
            name='status',
        ),
    ]
