# Generated by Django 2.2 on 2020-02-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200226_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogbook',
            name='logbook_items',
        ),
        migrations.AddField(
            model_name='studentlogbookitem',
            name='logbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.StudentLogBook'),
        ),
    ]
