# Generated by Django 2.2 on 2020-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200226_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogbook',
            name='label',
            field=models.CharField(default='Default Logbook', max_length=500, unique=True),
        ),
    ]
