# Generated by Django 2.2 on 2020-02-26 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentlogbook_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttachmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('street', models.CharField(default='', max_length=50)),
                ('lat', models.CharField(default='', max_length=100)),
                ('lng', models.CharField(default='', max_length=100)),
                ('info', models.CharField(default='', max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
            options={
                'verbose_name_plural': 'student_attachment_locations',
                'db_table': 'student_attachment_locations',
            },
        ),
    ]
